name: MaskCycleGAN-VC
channels:
  - pytorch
  - numba
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - absl-py
  - aiohttp
  - appdirs
  - astroid
  - async-timeout
  - attrs
  - audioread
  - autopep8
  - backcall
  - blas
  - blinker
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - click
  - cryptography
  - cudatoolkit
  - cycler
  - decorator
  - ffmpeg
  - flake8
  - freetype
  - gettext
  - gmp
  - gnutls
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - idna
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - isort
  - jedi
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lame
  - lazy-object-proxy
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libffi
  - libflac
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - liblapack
  - libogg
  - libopus
  - libpng
  - libprotobuf
  - librosa
  - libsndfile
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libvorbis
  - llvmlite
  - lz4-c
  - markdown
  - matplotlib-base
  - mccabe
  - mkl
  - multidict
  - ncurses
  - nettle
  - ninja
  - numba
  - numpy
  - oauthlib
  - olefile
  - openh264
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pooch
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pyflakes
  - pygments
  - pyjwt
  - pylint
  - pyopenssl
  - pyparsing
  - pysocks
  - pysoundfile
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pyzmq
  - readline
  - requests
  - requests-oauthlib
  - resampy
  - rope
  - rsa
  - scikit-learn
  - setuptools
  - six
  - sqlite
  - tensorboard
  - tensorboard-plugin-wit
  - tensorboardx
  - threadpoolctl
  - tk
  - toml
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - werkzeug
  - wheel
  - wrapt
  - x264
  - xz
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - argon2-cffi
    - async-generator
    - bleach
    - cython
    - defusedxml
    - entrypoints
    - iprogress
    - ipywidgets
    - jinja2
    - jsonschema
    - jupyterlab-pygments
    - jupyterlab-widgets
    - markupsafe
    - mistune
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - opencv-python
    - pandas
    - pandocfilters
    - prometheus-client
    - pyrsistent
    - pytz
    - pyworld
    - pyyaml
    - scipy
    - send2trash
    - sklearn
    - terminado
    - testpath
    - webencodings
    - widgetsnbextension
